// Copyright (c) 2026 FicForge Contributors
// Licensed under the GNU Affero General Public License v3.0.

/**
 * Context Assembler Golden Tests — 5 scenarios compared with Python output.
 * Golden values generated by Python context_assembler and saved in fixtures/.
 */

import { describe, expect, it, beforeEach } from "vitest";
import { readFileSync } from "fs";
import { assemble_context } from "../context_assembler.js";
import { createProject, createLLMConfig, createWritingStyle, createCastRegistry } from "../../domain/project.js";
import { createState } from "../../domain/state.js";
import { createFact } from "../../domain/fact.js";
import { createChapter } from "../../domain/chapter.js";
import { FactStatus, NarrativeWeight, FactType, FactSource } from "../../domain/enums.js";
import { MockAdapter } from "../../repositories/__tests__/mock_adapter.js";
import { FileChapterRepository } from "../../repositories/implementations/file_chapter.js";
import { compute_content_hash } from "../../repositories/implementations/file_utils.js";

const golden = JSON.parse(
  readFileSync(new URL("./fixtures/context_golden.json", import.meta.url), "utf-8"),
);

// Allow ±2 token variance (gpt-tokenizer vs tiktoken)
function assertTokensClose(actual: number, expected: number, label: string) {
  expect(Math.abs(actual - expected), `${label}: actual=${actual} expected=${expected}`).toBeLessThanOrEqual(2);
}

describe("Context Assembler Golden Tests", () => {
  let adapter: MockAdapter;
  let chapterRepo: FileChapterRepository;

  beforeEach(() => {
    adapter = new MockAdapter();
    chapterRepo = new FileChapterRepository(adapter);
  });

  it("Scene 3: Empty AU — first chapter, no history, no facts", async () => {
    const g = golden.scene3;
    const project = createProject({
      project_id: "p3", au_id: "scene3",
      llm: createLLMConfig({ mode: "api" as any, model: "gpt-4o", context_window: 32000 }),
      chapter_length: 1500,
    });
    const state = createState({ au_id: "scene3", current_chapter: 1 });

    const result = await assemble_context(project, state, "开始写第一章", [], chapterRepo, "scene3");

    expect(result.budget_report.context_window).toBe(g.budget.context_window);
    assertTokensClose(result.budget_report.system_tokens, g.budget.system_tokens, "system_tokens");
    assertTokensClose(result.budget_report.p1_tokens, g.budget.p1_tokens, "p1_tokens");
    expect(result.budget_report.p2_tokens).toBe(g.budget.p2_tokens);
    expect(result.budget_report.p3_tokens).toBe(g.budget.p3_tokens);
    expect(result.budget_report.p5_tokens).toBe(g.budget.p5_tokens);
    expect(result.budget_report.max_output_tokens).toBe(g.budget.max_output_tokens);
    expect(result.context_summary.pinned_count).toBe(g.summary.pinned_count);
    expect(result.context_summary.facts_injected).toBe(g.summary.facts_injected);
  });

  it("Scene 1: Normal — 3 chapters, 10 facts, characters, worldbuilding", async () => {
    const g = golden.scene1;

    // Save 3 chapters
    for (let i = 1; i <= 3; i++) {
      const c = ("第" + i + "章内容。").repeat(50);
      await chapterRepo.save(createChapter({
        au_id: "scene1", chapter_num: i, content: c,
        chapter_id: `id${i}`, provenance: "ai",
      }));
    }

    const facts = Array.from({ length: 10 }, (_, i) => createFact({
      id: `f${i + 1}`, content_raw: "r", content_clean: `事实${i + 1}内容描述`,
      characters: ["Alice"], chapter: (i % 3) + 1,
      status: i > 7 ? FactStatus.UNRESOLVED : FactStatus.ACTIVE,
      type: FactType.PLOT_EVENT,
      narrative_weight: i < 3 ? NarrativeWeight.HIGH : NarrativeWeight.MEDIUM,
    }));

    const project = createProject({
      project_id: "p1", au_id: "scene1",
      llm: createLLMConfig({ mode: "api" as any, model: "gpt-4o", context_window: 32000 }),
      chapter_length: 1500, pinned_context: ["铁律一"],
      core_always_include: ["Alice"], core_guarantee_budget: 400,
      cast_registry: createCastRegistry({ characters: ["Alice", "Bob"] }),
    });
    const state = createState({
      au_id: "scene1", current_chapter: 4, last_scene_ending: "他走了。",
      chapter_focus: ["f9"], characters_last_seen: { Alice: 3, Bob: 2 },
    });

    const result = await assemble_context(
      project, state, "继续写下一章", facts, chapterRepo, "scene1",
      null, { Alice: "# Alice\n角色设定内容", Bob: "# Bob\n配角设定" },
      { 世界观: "# 世界观\n设定内容" },
    );

    expect(result.budget_report.context_window).toBe(g.budget.context_window);
    assertTokensClose(result.budget_report.system_tokens, g.budget.system_tokens, "system_tokens");
    assertTokensClose(result.budget_report.p1_tokens, g.budget.p1_tokens, "p1_tokens");
    assertTokensClose(result.budget_report.p2_tokens, g.budget.p2_tokens, "p2_tokens");
    assertTokensClose(result.budget_report.p3_tokens, g.budget.p3_tokens, "p3_tokens");
    assertTokensClose(result.budget_report.p5_tokens, g.budget.p5_tokens, "p5_tokens");
    expect(result.budget_report.max_output_tokens).toBe(g.budget.max_output_tokens);
    expect(result.budget_report.unresolved_soft_degraded).toBe(g.budget.unresolved_soft_degraded);
    expect(result.context_summary.pinned_count).toBe(g.summary.pinned_count);
    expect(result.context_summary.facts_injected).toBe(g.summary.facts_injected);
    expect(result.context_summary.characters_used).toEqual(g.summary.characters_used);
    expect(result.context_summary.worldbuilding_used).toEqual(g.summary.worldbuilding_used);
  });

  it("Scene 2: Tight budget — 4096 context window, long pinned, soft degradation possible", async () => {
    const g = golden.scene2;
    const project = createProject({
      project_id: "p2", au_id: "scene2",
      llm: createLLMConfig({ mode: "api" as any, model: "gpt-4o", context_window: 4096 }),
      writing_style: createWritingStyle({ custom_instructions: "非常非常长的自定义指令".repeat(20) }),
      chapter_length: 800, pinned_context: ["长铁律".repeat(10)],
    });
    const state = createState({ au_id: "scene2", current_chapter: 1 });
    const facts = Array.from({ length: 5 }, (_, i) => createFact({
      id: `tf${i + 1}`, content_raw: "r", content_clean: `紧张预算事实${i + 1}`.repeat(5),
      chapter: 1, status: FactStatus.UNRESOLVED, type: FactType.FORESHADOWING,
      narrative_weight: NarrativeWeight.MEDIUM,
    }));

    const result = await assemble_context(project, state, "写", facts, chapterRepo, "scene2");

    expect(result.budget_report.context_window).toBe(g.budget.context_window);
    assertTokensClose(result.budget_report.system_tokens, g.budget.system_tokens, "system_tokens");
    assertTokensClose(result.budget_report.p1_tokens, g.budget.p1_tokens, "p1_tokens");
    assertTokensClose(result.budget_report.p3_tokens, g.budget.p3_tokens, "p3_tokens");
    expect(result.budget_report.max_output_tokens).toBe(g.budget.max_output_tokens);
    expect(result.context_summary.pinned_count).toBe(g.summary.pinned_count);
  });

  it("Scene 4: Many facts — 50 facts, sorting and truncation", async () => {
    const g = golden.scene4;
    const project = createProject({
      project_id: "p4", au_id: "scene4",
      llm: createLLMConfig({ mode: "api" as any, model: "gpt-4o", context_window: 32000 }),
      chapter_length: 1500,
    });
    const state = createState({ au_id: "scene4", current_chapter: 1 });
    const facts = Array.from({ length: 50 }, (_, i) => createFact({
      id: `mf${i}`, content_raw: "r", content_clean: `大量事实第${i}条描述内容`,
      chapter: (i % 10) + 1,
      status: i % 3 === 0 ? FactStatus.UNRESOLVED : FactStatus.ACTIVE,
      type: FactType.PLOT_EVENT,
      narrative_weight: [NarrativeWeight.HIGH, NarrativeWeight.MEDIUM, NarrativeWeight.LOW][i % 3],
    }));

    const result = await assemble_context(project, state, "继续", facts, chapterRepo, "scene4");

    expect(result.budget_report.context_window).toBe(g.budget.context_window);
    assertTokensClose(result.budget_report.p3_tokens, g.budget.p3_tokens, "p3_tokens");
    expect(result.context_summary.facts_injected).toBe(g.summary.facts_injected);
    expect(result.budget_report.unresolved_soft_degraded).toBe(g.budget.unresolved_soft_degraded);
  });

  it("Scene 5: core_guarantee_budget — long character file triggers guarantee", async () => {
    const g = golden.scene5;
    const project = createProject({
      project_id: "p5", au_id: "scene5",
      llm: createLLMConfig({ mode: "api" as any, model: "gpt-4o", context_window: 8000 }),
      chapter_length: 1000,
      cast_registry: createCastRegistry({ characters: ["主角", "配角"] }),
      core_always_include: ["主角"], core_guarantee_budget: 400,
    });
    const state = createState({ au_id: "scene5", current_chapter: 1 });
    const longChar = "# 主角\n" + "这是一段很长的角色设定。".repeat(100);

    const result = await assemble_context(
      project, state, "写", [], chapterRepo, "scene5",
      null, { 主角: longChar, 配角: "# 配角\n短设定" },
    );

    expect(result.budget_report.context_window).toBe(g.budget.context_window);
    assertTokensClose(result.budget_report.p5_tokens, g.budget.p5_tokens, "p5_tokens");
    expect(result.budget_report.max_output_tokens).toBe(g.budget.max_output_tokens);
    expect(result.context_summary.characters_used).toEqual(g.summary.characters_used);
    expect(result.context_summary.truncated_characters).toEqual(g.summary.truncated_characters);
  });
});
